// Plain-language image descriptions, kept separate from the illustration briefs.
export const descriptions = [
  'A purple-and-yellow planet hangs in space, its hills dotted with gray rock homes.',
  'Hooded Yips sing together, grinning beneath long noses. Their eyes disappear into the shadows of their hoods.',
  'Bare toes shuffle rapidly beneath the hems of long robes.',
  'A smiling Yip opens a gray rock home on a purple hillside.',
  'A yellow street curls up and down purple hills between clusters of gray boulders.',
  'Purple-and-yellow banners decorate the rock shops and cinema along a busy street.',
  'A cup of purple ploofidonk and a yellow brog patty sit on a café table.',
  'Two Yips gesture enthusiastically to each other, both wearing enormous toothy smiles.',
  'A lime-green, blimp-shaped spaceship looms over the Yips’ town.',
  'A huge green Gorf holds a tiny orange pistol. Bubbles and distorted scenery are visible through its translucent goo.',
  'The Gorf leader bends down to address a cheerful Yip.',
  'A Yip leads the Gorf to the largest rock in town, where the royal Yip waits.',
  'The Gorf leader bows before the smiling royal Yip and the assembled court.',
  'The translucent Gorf speaks politely beside the still-cheerful royal Yip.',
  'The Gorf holds its orange weapon toward a smiling Yip outside a rock home.',
  'Another Yip smiles at the Gorf outside a rock shop while more Yips wait behind.',
  'Five Yips in distinct purple-and-yellow robes stand together before the Gorf.',
  'The tall, pointed-hood Yip’s smile has become a short, downturned line. The other four stand behind.',
  'All five Nerps stand in a row with gloomy mouths and their eyes hidden in shadow.',
  'A broad Yip grin is shown beside a Nerp’s small frown.',
  'The five Nerps approach the open entrance of an enormous gray rock spaceship.',
  'A large red button sits among many small yellow buttons on a purple control console.',
  'A plum-robed sleeve presses the red button while the other four Nerps watch.',
  'The giant rock ship flies away from Flummoxprap into space.',
  'Five silent Nerps watch their purple-and-yellow home recede through the ship’s window.',
  'Earth fills the window as the Nerps gather around a planning table.',
  'A robed sleeve opens a drawer containing an invisibility button.',
  'A huge inflatable sumo costume is laid out, with places for a Nerp in each limb and one in the center.',
  'A Nerp finds an empty weapon rack where a laser gun should have been.',
  'The Nerps solemnly examine a brightly colored toy foam-dart gun.',
  'The five Nerps prepare the invisibility button, inflatable costume, and small toy gun.',
  'The rock ship fades to a ghostly outline as it approaches Earth.',
  'A Japanese city street surrounds a 7-Eleven with a flat roof.',
  'The five Nerps stand on the store’s roof beside the faint outline of their invisible ship.',
  'The Nerps unfold an enormous, empty sumo wrestler costume.',
  'Four Nerps squeeze awkwardly into the costume’s arms and legs as the fifth waits.',
  'The final Nerp squeezes into the center of the now-lumpy costume.',
  'The inflatable disguise waddles along the street with its limbs at awkward angles.',
  'Passersby give the unusually lumpy costume puzzled glances.',
  'The costume waits at elevator doors, with the tiny toy gun poking out.',
  'Inside the elevator, the costume presses buttons to ride up and down.',
  'An elderly man with glasses and a cane joins the costume in the elevator.',
  'A long-nosed Nerp’s hooded head suddenly pokes out of the costume.',
  'A soft foam dart lightly hits the elderly man’s jacket.',
  'Unharmed, the man adjusts his glasses and looks down in confusion.',
  'More soft darts bounce off the man’s coat and scatter on the elevator floor.',
  'The doors open, and the man calmly leaves the elevator with his cane.',
  'The Nerp peers from the costume, toy gun raised, surveying the now-empty doorway.',
  'The costume waddles out into a street darkening with evening shadows.',
  'A small house sits beneath a bridge on a quiet side street.',
  'The house has faded navy-blue walls, a rusty white fence, a hazy window, and a patch of dead grass.',
  'A crooked warning sign hangs from the chipped white fence.',
  'The five Nerps, now out of the costume, straighten the warning sign.',
  'The front window looks hazy from the street, with the sofa barely visible close to the glass.',
  'The five Nerps enter a small doorway and discover an impossibly enormous room.',
  'A large sofa stands beside the front window. A dark doorway opens in the back-right corner.',
  'The five Nerps huddle conspiratorially in the huge back room.',
  'Covered sleeves work rapidly on a strange conveyor machine.',
  'An empty human-sized hopper feeds a long conveyor belt ending at a table.',
  'A Nerp holds the same harmless toy gun in the dim room, with soft darts nearby.',
  'The machine’s completely empty hopper leads into its dark interior.',
  'A small open cardboard box holds one toy gun and exactly three foam darts.',
  'The five Nerps shuffle from the back room toward the sofa.',
  'Seen through the front window at night, all five Nerps sit together on the sofa, waiting. Nobody approaches.'
];
